FROM golang:1.25.4-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/worker ./cmd/worker

FROM alpine:3.22

WORKDIR /app
COPY --from=builder /out/worker /app/worker

EXPOSE 50051
ENTRYPOINT ["/app/worker"]
