FROM golang:1.25.4-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/gateway ./cmd/gateway

FROM alpine:3.22

WORKDIR /app
COPY --from=builder /out/gateway /app/gateway

EXPOSE 8081
ENTRYPOINT ["/app/gateway"]
