// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/weather.proto

package weatherpb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentWeatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentWeatherRequest) Reset() {
	*x = GetCurrentWeatherRequest{}
	mi := &file_proto_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentWeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentWeatherRequest) ProtoMessage() {}

func (x *GetCurrentWeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentWeatherRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentWeatherRequest) Descriptor() ([]byte, []int) {
	return file_proto_weather_proto_rawDescGZIP(), []int{0}
}

func (x *GetCurrentWeatherRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type GetCurrentWeatherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	TemperatureC  float64                `protobuf:"fixed64,2,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"`
	WindSpeedMs   float64                `protobuf:"fixed64,3,opt,name=wind_speed_ms,json=windSpeedMs,proto3" json:"wind_speed_ms,omitempty"`
	WeatherCode   int32                  `protobuf:"varint,4,opt,name=weather_code,json=weatherCode,proto3" json:"weather_code,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentWeatherResponse) Reset() {
	*x = GetCurrentWeatherResponse{}
	mi := &file_proto_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentWeatherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentWeatherResponse) ProtoMessage() {}

func (x *GetCurrentWeatherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentWeatherResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentWeatherResponse) Descriptor() ([]byte, []int) {
	return file_proto_weather_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentWeatherResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetCurrentWeatherResponse) GetTemperatureC() float64 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

func (x *GetCurrentWeatherResponse) GetWindSpeedMs() float64 {
	if x != nil {
		return x.WindSpeedMs
	}
	return 0
}

func (x *GetCurrentWeatherResponse) GetWeatherCode() int32 {
	if x != nil {
		return x.WeatherCode
	}
	return 0
}

func (x *GetCurrentWeatherResponse) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

type GetForecastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Days          int32                  `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastRequest) Reset() {
	*x = GetForecastRequest{}
	mi := &file_proto_weather_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastRequest) ProtoMessage() {}

func (x *GetForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weather_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastRequest.ProtoReflect.Descriptor instead.
func (*GetForecastRequest) Descriptor() ([]byte, []int) {
	return file_proto_weather_proto_rawDescGZIP(), []int{2}
}

func (x *GetForecastRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetForecastRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type GetForecastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Days          []*DailyForecast       `protobuf:"bytes,2,rep,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastResponse) Reset() {
	*x = GetForecastResponse{}
	mi := &file_proto_weather_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastResponse) ProtoMessage() {}

func (x *GetForecastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weather_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastResponse.ProtoReflect.Descriptor instead.
func (*GetForecastResponse) Descriptor() ([]byte, []int) {
	return file_proto_weather_proto_rawDescGZIP(), []int{3}
}

func (x *GetForecastResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetForecastResponse) GetDays() []*DailyForecast {
	if x != nil {
		return x.Days
	}
	return nil
}

type DailyForecast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	TMin          float64                `protobuf:"fixed64,2,opt,name=t_min,json=tMin,proto3" json:"t_min,omitempty"`
	TMax          float64                `protobuf:"fixed64,3,opt,name=t_max,json=tMax,proto3" json:"t_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyForecast) Reset() {
	*x = DailyForecast{}
	mi := &file_proto_weather_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyForecast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyForecast) ProtoMessage() {}

func (x *DailyForecast) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weather_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyForecast.ProtoReflect.Descriptor instead.
func (*DailyForecast) Descriptor() ([]byte, []int) {
	return file_proto_weather_proto_rawDescGZIP(), []int{4}
}

func (x *DailyForecast) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyForecast) GetTMin() float64 {
	if x != nil {
		return x.TMin
	}
	return 0
}

func (x *DailyForecast) GetTMax() float64 {
	if x != nil {
		return x.TMax
	}
	return 0
}

var File_proto_weather_proto protoreflect.FileDescriptor

const file_proto_weather_proto_rawDesc = "" +
	"\n" +
	"\x13proto/weather.proto\x12\n" +
	"weather.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"9\n" +
	"\x18GetCurrentWeatherRequest\x12\x1d\n" +
	"\x04city\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x18@R\x04city\"\xd8\x01\n" +
	"\x19GetCurrentWeatherResponse\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12#\n" +
	"\rtemperature_c\x18\x02 \x01(\x01R\ftemperatureC\x12\"\n" +
	"\rwind_speed_ms\x18\x03 \x01(\x01R\vwindSpeedMs\x12!\n" +
	"\fweather_code\x18\x04 \x01(\x05R\vweatherCode\x12;\n" +
	"\vobserved_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"R\n" +
	"\x12GetForecastRequest\x12\x1d\n" +
	"\x04city\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x18@R\x04city\x12\x1d\n" +
	"\x04days\x18\x02 \x01(\x05B\t\xbaH\x06\x1a\x04\x18\x0e(\x01R\x04days\"X\n" +
	"\x13GetForecastResponse\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12-\n" +
	"\x04days\x18\x02 \x03(\v2\x19.weather.v1.DailyForecastR\x04days\"M\n" +
	"\rDailyForecast\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x13\n" +
	"\x05t_min\x18\x02 \x01(\x01R\x04tMin\x12\x13\n" +
	"\x05t_max\x18\x03 \x01(\x01R\x04tMax2\xc2\x01\n" +
	"\x0eWeatherService\x12`\n" +
	"\x11GetCurrentWeather\x12$.weather.v1.GetCurrentWeatherRequest\x1a%.weather.v1.GetCurrentWeatherResponse\x12N\n" +
	"\vGetForecast\x12\x1e.weather.v1.GetForecastRequest\x1a\x1f.weather.v1.GetForecastResponseB\x19Z\x17weather/proto;weatherpbb\x06proto3"

var (
	file_proto_weather_proto_rawDescOnce sync.Once
	file_proto_weather_proto_rawDescData []byte
)

func file_proto_weather_proto_rawDescGZIP() []byte {
	file_proto_weather_proto_rawDescOnce.Do(func() {
		file_proto_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_weather_proto_rawDesc), len(file_proto_weather_proto_rawDesc)))
	})
	return file_proto_weather_proto_rawDescData
}

var file_proto_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_weather_proto_goTypes = []any{
	(*GetCurrentWeatherRequest)(nil),  // 0: weather.v1.GetCurrentWeatherRequest
	(*GetCurrentWeatherResponse)(nil), // 1: weather.v1.GetCurrentWeatherResponse
	(*GetForecastRequest)(nil),        // 2: weather.v1.GetForecastRequest
	(*GetForecastResponse)(nil),       // 3: weather.v1.GetForecastResponse
	(*DailyForecast)(nil),             // 4: weather.v1.DailyForecast
	(*timestamppb.Timestamp)(nil),     // 5: google.protobuf.Timestamp
}
var file_proto_weather_proto_depIdxs = []int32{
	5, // 0: weather.v1.GetCurrentWeatherResponse.observed_at:type_name -> google.protobuf.Timestamp
	4, // 1: weather.v1.GetForecastResponse.days:type_name -> weather.v1.DailyForecast
	0, // 2: weather.v1.WeatherService.GetCurrentWeather:input_type -> weather.v1.GetCurrentWeatherRequest
	2, // 3: weather.v1.WeatherService.GetForecast:input_type -> weather.v1.GetForecastRequest
	1, // 4: weather.v1.WeatherService.GetCurrentWeather:output_type -> weather.v1.GetCurrentWeatherResponse
	3, // 5: weather.v1.WeatherService.GetForecast:output_type -> weather.v1.GetForecastResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_weather_proto_init() }
func file_proto_weather_proto_init() {
	if File_proto_weather_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_weather_proto_rawDesc), len(file_proto_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_weather_proto_goTypes,
		DependencyIndexes: file_proto_weather_proto_depIdxs,
		MessageInfos:      file_proto_weather_proto_msgTypes,
	}.Build()
	File_proto_weather_proto = out.File
	file_proto_weather_proto_goTypes = nil
	file_proto_weather_proto_depIdxs = nil
}
